services:
  - type: web
    name: resume-screening-app
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn final:app
    envVars:
      - key: FLASK_ENV
        value: production
  
